"""criar tabelas produtos e pedidos

Revision ID: 7d020ad6ed93
Revises: 
Create Date: 2025-04-30 21:33:45.559609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d020ad6ed93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id_produto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('id_market', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_produto')
    )
    op.create_table('pedidos',
    sa.Column('id_pedido', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('qnt_itens', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('Novo', 'Processando', 'Enviado', 'Cancelado'), nullable=True),
    sa.ForeignKeyConstraint(['id_produto'], ['produtos.id_produto'], ),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidos')
    op.drop_table('produtos')
    # ### end Alembic commands ###
