"""Tabelas Prontas

Revision ID: 958ad352dc35
Revises: 
Create Date: 2025-05-02 00:49:23.240335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
import bcrypt


# revision identifiers, used by Alembic.
revision = '958ad352dc35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
                    sa.Column('id_produto', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('nome', sa.String(length=100), nullable=False),
                    sa.Column('descricao', sa.Text(), nullable=True),
                    sa.Column('price', sa.Numeric(
                        precision=12, scale=2), nullable=False),
                    sa.Column('stock', sa.Integer(), nullable=False),
                    sa.Column('id_market', sa.String(
                        length=50), nullable=False, unique=True),
                    sa.PrimaryKeyConstraint('id_produto')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('nome', sa.String(length=255), nullable=False),
                    sa.Column('role', sa.Enum('USER', 'ADMIN',
                                              name='roleenum'), nullable=False),
                    sa.Column('senha_hash', sa.String(
                        length=60), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('carrinho',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('produto_id', sa.Integer(), nullable=False),
                    sa.Column('qnt_itens', sa.Integer(), nullable=False),
                    sa.Column('criado_em', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['produto_id'], ['produtos.id_produto'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('pedidos',
                    sa.Column('id_pedido', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('id_user', sa.Integer(), nullable=False),
                    sa.Column('id_produto', sa.Integer(), nullable=False),
                    sa.Column('qnt_itens', sa.Integer(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('status', sa.Enum('Novo', 'Processando',
                                                'Enviado', 'Cancelado'), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['id_produto'], ['produtos.id_produto'], ),
                    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id_pedido')
                    )
    # ### end Alembic commands ###

    # Adicionando seeds após criar a tabela
    users_table = table(
        'users',
        column('nome', sa.String),
        column('role', sa.Enum('USER', 'ADMIN', name='roleenum')),
        column('senha_hash', sa.String)
    )

    # Gerando hashes com bcrypt (igual ao seu modelo)
    admin_hash = bcrypt.hashpw(
        b'admin', bcrypt.gensalt()).decode('utf-8')
    user_hash = bcrypt.hashpw(b'user',
                              bcrypt.gensalt()).decode('utf-8')

    op.bulk_insert(users_table,
                   [
                       {'nome': 'Administrador', 'role': 'ADMIN',
                           'senha_hash': admin_hash},
                       {'nome': 'Usuário Comum', 'role': 'USER',
                           'senha_hash': user_hash}
                   ]
                   )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidos')
    op.drop_table('carrinho')
    op.drop_table('users')
    op.drop_table('produtos')
    # ### end Alembic commands ###
